const countryData = <Map>[
  <String, dynamic>{'id': 0, 'code': 'af', 'name': 'Afghanistan'},
  <String, dynamic>{'id': 1, 'code': 'ax', 'name': 'Aland Islands'},
  <String, dynamic>{'id': 2, 'code': 'al', 'name': 'Albania'},
  <String, dynamic>{'id': 3, 'code': 'dz', 'name': 'Algeria'},
  <String, dynamic>{'id': 4, 'code': 'as', 'name': 'American Samoa'},
  <String, dynamic>{'id': 5, 'code': 'ad', 'name': 'Andorra'},
  <String, dynamic>{'id': 6, 'code': 'ao', 'name': 'Angola'},
  <String, dynamic>{'id': 7, 'code': 'ai', 'name': 'Anguilla'},
  <String, dynamic>{'id': 8, 'code': 'ag', 'name': 'Antigua And Barbuda'},
  <String, dynamic>{'id': 9, 'code': 'ar', 'name': 'Argentina'},
  <String, dynamic>{'id': 10, 'code': 'am', 'name': 'Armenia'},
  <String, dynamic>{'id': 11, 'code': 'aw', 'name': 'Aruba'},
  <String, dynamic>{'id': 12, 'code': 'au', 'name': 'Australia'},
  <String, dynamic>{'id': 13, 'code': 'at', 'name': 'Austria'},
  <String, dynamic>{'id': 14, 'code': 'az', 'name': 'Azerbaijan'},
  <String, dynamic>{'id': 15, 'code': 'bs', 'name': 'Bahamas'},
  <String, dynamic>{'id': 16, 'code': 'bh', 'name': 'Bahrain'},
  <String, dynamic>{'id': 17, 'code': 'bd', 'name': 'Bangladesh'},
  <String, dynamic>{'id': 18, 'code': 'bb', 'name': 'Barbados'},
  <String, dynamic>{'id': 19, 'code': 'by', 'name': 'Belarus'},
  <String, dynamic>{'id': 20, 'code': 'be', 'name': 'Belgium'},
  <String, dynamic>{'id': 21, 'code': 'bz', 'name': 'Belize'},
  <String, dynamic>{'id': 22, 'code': 'bj', 'name': 'Benin'},
  <String, dynamic>{'id': 23, 'code': 'bm', 'name': 'Bermuda'},
  <String, dynamic>{'id': 24, 'code': 'bt', 'name': 'Bhutan'},
  <String, dynamic>{'id': 25, 'code': 'bo', 'name': 'Bolivia'},
  <String, dynamic>{'id': 26, 'code': 'ba', 'name': 'Bosnia And Herzegovina'},
  <String, dynamic>{'id': 27, 'code': 'bw', 'name': 'Botswana'},
  <String, dynamic>{'id': 28, 'code': 'bv', 'name': 'Bouvet Island'},
  <String, dynamic>{'id': 29, 'code': 'br', 'name': 'Brazil'},
  <String, dynamic>{'id': 30, 'code': 'io', 'name': 'British Indian Ocean Territory'},
  <String, dynamic>{'id': 31, 'code': 'bn', 'name': 'Brunei Darussalam'},
  <String, dynamic>{'id': 32, 'code': 'bg', 'name': 'Bulgaria'},
  <String, dynamic>{'id': 33, 'code': 'bf', 'name': 'Burkina Faso'},
  <String, dynamic>{'id': 34, 'code': 'bi', 'name': 'Burundi'},
  <String, dynamic>{'id': 35, 'code': 'kh', 'name': 'Cambodia'},
  <String, dynamic>{'id': 36, 'code': 'cm', 'name': 'Cameroon'},
  <String, dynamic>{'id': 37, 'code': 'ca', 'name': 'Canada'},
  <String, dynamic>{'id': 38, 'code': 'cv', 'name': 'Cape Verde'},
  <String, dynamic>{'id': 39, 'code': 'ky', 'name': 'Cayman Islands'},
  <String, dynamic>{'id': 40, 'code': 'cf', 'name': 'Central African Republic'},
  <String, dynamic>{'id': 41, 'code': 'td', 'name': 'Chad'},
  <String, dynamic>{'id': 42, 'code': 'cl', 'name': 'Chile'},
  <String, dynamic>{'id': 43, 'code': 'cn', 'name': 'China'},
  <String, dynamic>{'id': 44, 'code': 'cx', 'name': 'Christmas Island'},
  <String, dynamic>{'id': 45, 'code': 'cc', 'name': 'Cocos (Keeling) Islands'},
  <String, dynamic>{'id': 46, 'code': 'co', 'name': 'Colombia'},
  <String, dynamic>{'id': 47, 'code': 'km', 'name': 'Comoros'},
  <String, dynamic>{'id': 48, 'code': 'cg', 'name': 'Congo'},
  <String, dynamic>{'id': 49, 'code': 'cd', 'name': 'Congo, Democratic Republic'},
  <String, dynamic>{'id': 50, 'code': 'ck', 'name': 'Cook Islands'},
  <String, dynamic>{'id': 51, 'code': 'cr', 'name': 'Costa Rica'},
  <String, dynamic>{'id': 52, 'code': 'ci', 'name': "Cote D'Ivoire"},
  <String, dynamic>{'id': 53, 'code': 'hr', 'name': 'Croatia'},
  <String, dynamic>{'id': 54, 'code': 'cu', 'name': 'Cuba'},
  <String, dynamic>{'id': 55, 'code': 'cy', 'name': 'Cyprus'},
  <String, dynamic>{'id': 56, 'code': 'cz', 'name': 'Czech Republic'},
  <String, dynamic>{'id': 57, 'code': 'dk', 'name': 'Denmark'},
  <String, dynamic>{'id': 58, 'code': 'dj', 'name': 'Djibouti'},
  <String, dynamic>{'id': 59, 'code': 'dm', 'name': 'Dominica'},
  <String, dynamic>{'id': 60, 'code': 'do', 'name': 'Dominican Republic'},
  <String, dynamic>{'id': 61, 'code': 'ec', 'name': 'Ecuador'},
  <String, dynamic>{'id': 62, 'code': 'eg', 'name': 'Egypt'},
  <String, dynamic>{'id': 63, 'code': 'sv', 'name': 'El Salvador'},
  <String, dynamic>{'id': 64, 'code': 'gq', 'name': 'Equatorial Guinea'},
  <String, dynamic>{'id': 65, 'code': 'er', 'name': 'Eritrea'},
  <String, dynamic>{'id': 66, 'code': 'ee', 'name': 'Estonia'},
  <String, dynamic>{'id': 67, 'code': 'et', 'name': 'Ethiopia'},
  <String, dynamic>{'id': 68, 'code': 'fk', 'name': 'Falkland Islands (Malvinas)'},
  <String, dynamic>{'id': 69, 'code': 'fo', 'name': 'Faroe Islands'},
  <String, dynamic>{'id': 70, 'code': 'fj', 'name': 'Fiji'},
  <String, dynamic>{'id': 71, 'code': 'fi', 'name': 'Finland'},
  <String, dynamic>{'id': 72, 'code': 'fr', 'name': 'France'},
  <String, dynamic>{'id': 73, 'code': 'gf', 'name': 'French Guiana'},
  <String, dynamic>{'id': 74, 'code': 'pf', 'name': 'French Polynesia'},
  <String, dynamic>{'id': 75, 'code': 'tf', 'name': 'French Southern Territories'},
  <String, dynamic>{'id': 76, 'code': 'ga', 'name': 'Gabon'},
  <String, dynamic>{'id': 77, 'code': 'gm', 'name': 'Gambia'},
  <String, dynamic>{'id': 78, 'code': 'ge', 'name': 'Georgia'},
  <String, dynamic>{'id': 79, 'code': 'de', 'name': 'Germany'},
  <String, dynamic>{'id': 80, 'code': 'gh', 'name': 'Ghana'},
  <String, dynamic>{'id': 81, 'code': 'gi', 'name': 'Gibraltar'},
  <String, dynamic>{'id': 82, 'code': 'gr', 'name': 'Greece'},
  <String, dynamic>{'id': 83, 'code': 'gl', 'name': 'Greenland'},
  <String, dynamic>{'id': 84, 'code': 'gd', 'name': 'Grenada'},
  <String, dynamic>{'id': 85, 'code': 'gp', 'name': 'Guadeloupe'},
  <String, dynamic>{'id': 86, 'code': 'gu', 'name': 'Guam'},
  <String, dynamic>{'id': 87, 'code': 'gt', 'name': 'Guatemala'},
  <String, dynamic>{'id': 88, 'code': 'gg', 'name': 'Guernsey'},
  <String, dynamic>{'id': 89, 'code': 'gn', 'name': 'Guinea'},
  <String, dynamic>{'id': 90, 'code': 'gw', 'name': 'GuineaBissau'},
  <String, dynamic>{'id': 91, 'code': 'gy', 'name': 'Guyana'},
  <String, dynamic>{'id': 92, 'code': 'ht', 'name': 'Haiti'},
  <String, dynamic>{'id': 93, 'code': 'hm', 'name': 'Heard Island & Mcdonald Islands'},
  <String, dynamic>{'id': 94, 'code': 'va', 'name': 'Holy See (Vatican City State)'},
  <String, dynamic>{'id': 95, 'code': 'hn', 'name': 'Honduras'},
  <String, dynamic>{'id': 96, 'code': 'hk', 'name': 'Hong Kong'},
  <String, dynamic>{'id': 97, 'code': 'hu', 'name': 'Hungary'},
  <String, dynamic>{'id': 98, 'code': 'is', 'name': 'Iceland'},
  <String, dynamic>{'id': 99, 'code': 'in', 'name': 'India'},
  <String, dynamic>{'id': 100, 'code': 'id', 'name': 'Indonesia'},
  <String, dynamic>{'id': 101, 'code': 'ir', 'name': 'Iran, Islamic Republic Of'},
  <String, dynamic>{'id': 102, 'code': 'iq', 'name': 'Iraq'},
  <String, dynamic>{'id': 103, 'code': 'ie', 'name': 'Ireland'},
  <String, dynamic>{'id': 104, 'code': 'im', 'name': 'Isle Of Man'},
  <String, dynamic>{'id': 105, 'code': 'il', 'name': 'Israel'},
  <String, dynamic>{'id': 106, 'code': 'it', 'name': 'Italy'},
  <String, dynamic>{'id': 107, 'code': 'jm', 'name': 'Jamaica'},
  <String, dynamic>{'id': 108, 'code': 'jp', 'name': 'Japan'},
  <String, dynamic>{'id': 109, 'code': 'je', 'name': 'Jersey'},
  <String, dynamic>{'id': 110, 'code': 'jo', 'name': 'Jordan'},
  <String, dynamic>{'id': 111, 'code': 'kz', 'name': 'Kazakhstan'},
  <String, dynamic>{'id': 112, 'code': 'ke', 'name': 'Kenya'},
  <String, dynamic>{'id': 113, 'code': 'ki', 'name': 'Kiribati'},
  <String, dynamic>{'id': 114, 'code': 'kr', 'name': 'Korea'},
  <String, dynamic>{'id': 115, 'code': 'kw', 'name': 'Kuwait'},
  <String, dynamic>{'id': 116, 'code': 'kg', 'name': 'Kyrgyzstan'},
  <String, dynamic>{'id': 117, 'code': 'la', 'name': "Lao People's Democratic Republic"},
  <String, dynamic>{'id': 118, 'code': 'lv', 'name': 'Latvia'},
  <String, dynamic>{'id': 119, 'code': 'lb', 'name': 'Lebanon'},
  <String, dynamic>{'id': 120, 'code': 'ls', 'name': 'Lesotho'},
  <String, dynamic>{'id': 121, 'code': 'lr', 'name': 'Liberia'},
  <String, dynamic>{'id': 122, 'code': 'ly', 'name': 'Libyan Arab Jamahiriya'},
  <String, dynamic>{'id': 123, 'code': 'li', 'name': 'Liechtenstein'},
  <String, dynamic>{'id': 124, 'code': 'lt', 'name': 'Lithuania'},
  <String, dynamic>{'id': 125, 'code': 'lu', 'name': 'Luxembourg'},
  <String, dynamic>{'id': 126, 'code': 'mo', 'name': 'Macao'},
  <String, dynamic>{'id': 127, 'code': 'mk', 'name': 'Macedonia'},
  <String, dynamic>{'id': 128, 'code': 'mg', 'name': 'Madagascar'},
  <String, dynamic>{'id': 129, 'code': 'mw', 'name': 'Malawi'},
  <String, dynamic>{'id': 130, 'code': 'my', 'name': 'Malaysia'},
  <String, dynamic>{'id': 131, 'code': 'mv', 'name': 'Maldives'},
  <String, dynamic>{'id': 132, 'code': 'ml', 'name': 'Mali'},
  <String, dynamic>{'id': 133, 'code': 'mt', 'name': 'Malta'},
  <String, dynamic>{'id': 134, 'code': 'mh', 'name': 'Marshall Islands'},
  <String, dynamic>{'id': 135, 'code': 'mq', 'name': 'Martinique'},
  <String, dynamic>{'id': 136, 'code': 'mr', 'name': 'Mauritania'},
  <String, dynamic>{'id': 137, 'code': 'mu', 'name': 'Mauritius'},
  <String, dynamic>{'id': 138, 'code': 'yt', 'name': 'Mayotte'},
  <String, dynamic>{'id': 139, 'code': 'mx', 'name': 'Mexico'},
  <String, dynamic>{'id': 140, 'code': 'fm', 'name': 'Micronesia, Federated States Of'},
  <String, dynamic>{'id': 141, 'code': 'md', 'name': 'Moldova'},
  <String, dynamic>{'id': 142, 'code': 'mc', 'name': 'Monaco'},
  <String, dynamic>{'id': 143, 'code': 'mn', 'name': 'Mongolia'},
  <String, dynamic>{'id': 144, 'code': 'me', 'name': 'Montenegro'},
  <String, dynamic>{'id': 145, 'code': 'ms', 'name': 'Montserrat'},
  <String, dynamic>{'id': 146, 'code': 'ma', 'name': 'Morocco'},
  <String, dynamic>{'id': 147, 'code': 'mz', 'name': 'Mozambique'},
  <String, dynamic>{'id': 148, 'code': 'mm', 'name': 'Myanmar'},
  <String, dynamic>{'id': 149, 'code': 'na', 'name': 'Namibia'},
  <String, dynamic>{'id': 150, 'code': 'nr', 'name': 'Nauru'},
  <String, dynamic>{'id': 151, 'code': 'np', 'name': 'Nepal'},
  <String, dynamic>{'id': 152, 'code': 'nl', 'name': 'Netherlands'},
  <String, dynamic>{'id': 153, 'code': 'an', 'name': 'Netherlands Antilles'},
  <String, dynamic>{'id': 154, 'code': 'nc', 'name': 'New Caledonia'},
  <String, dynamic>{'id': 155, 'code': 'nz', 'name': 'New Zealand'},
  <String, dynamic>{'id': 156, 'code': 'ni', 'name': 'Nicaragua'},
  <String, dynamic>{'id': 157, 'code': 'ne', 'name': 'Niger'},
  <String, dynamic>{'id': 158, 'code': 'ng', 'name': 'Nigeria'},
  <String, dynamic>{'id': 159, 'code': 'nu', 'name': 'Niue'},
  <String, dynamic>{'id': 160, 'code': 'nf', 'name': 'Norfolk Island'},
  <String, dynamic>{'id': 161, 'code': 'mp', 'name': 'Northern Mariana Islands'},
  <String, dynamic>{'id': 162, 'code': 'no', 'name': 'Norway'},
  <String, dynamic>{'id': 163, 'code': 'om', 'name': 'Oman'},
  <String, dynamic>{'id': 164, 'code': 'pk', 'name': 'Pakistan'},
  <String, dynamic>{'id': 165, 'code': 'pw', 'name': 'Palau'},
  <String, dynamic>{'id': 166, 'code': 'ps', 'name': 'Palestinian Territory, Occupied'},
  <String, dynamic>{'id': 167, 'code': 'pa', 'name': 'Panama'},
  <String, dynamic>{'id': 168, 'code': 'pg', 'name': 'Papua New Guinea'},
  <String, dynamic>{'id': 169, 'code': 'py', 'name': 'Paraguay'},
  <String, dynamic>{'id': 170, 'code': 'pe', 'name': 'Peru'},
  <String, dynamic>{'id': 171, 'code': 'ph', 'name': 'Philippines'},
  <String, dynamic>{'id': 172, 'code': 'pn', 'name': 'Pitcairn'},
  <String, dynamic>{'id': 173, 'code': 'pl', 'name': 'Poland'},
  <String, dynamic>{'id': 174, 'code': 'pt', 'name': 'Portugal'},
  <String, dynamic>{'id': 175, 'code': 'pr', 'name': 'Puerto Rico'},
  <String, dynamic>{'id': 176, 'code': 'qa', 'name': 'Qatar'},
  <String, dynamic>{'id': 177, 'code': 're', 'name': 'Reunion'},
  <String, dynamic>{'id': 178, 'code': 'ro', 'name': 'Romania'},
  <String, dynamic>{'id': 179, 'code': 'ru', 'name': 'Russian Federation'},
  <String, dynamic>{'id': 180, 'code': 'rw', 'name': 'Rwanda'},
  <String, dynamic>{'id': 181, 'code': 'bl', 'name': 'Saint Barthelemy'},
  <String, dynamic>{'id': 182, 'code': 'sh', 'name': 'Saint Helena'},
  <String, dynamic>{'id': 183, 'code': 'kn', 'name': 'Saint Kitts And Nevis'},
  <String, dynamic>{'id': 184, 'code': 'lc', 'name': 'Saint Lucia'},
  <String, dynamic>{'id': 185, 'code': 'mf', 'name': 'Saint Martin'},
  <String, dynamic>{'id': 186, 'code': 'pm', 'name': 'Saint Pierre And Miquelon'},
  <String, dynamic>{'id': 187, 'code': 'vc', 'name': 'Saint Vincent And Grenadines'},
  <String, dynamic>{'id': 188, 'code': 'ws', 'name': 'Samoa'},
  <String, dynamic>{'id': 189, 'code': 'sm', 'name': 'San Marino'},
  <String, dynamic>{'id': 190, 'code': 'st', 'name': 'Sao Tome And Principe'},
  <String, dynamic>{'id': 191, 'code': 'sa', 'name': 'Saudi Arabia'},
  <String, dynamic>{'id': 192, 'code': 'sn', 'name': 'Senegal'},
  <String, dynamic>{'id': 193, 'code': 'rs', 'name': 'Serbia'},
  <String, dynamic>{'id': 194, 'code': 'sc', 'name': 'Seychelles'},
  <String, dynamic>{'id': 195, 'code': 'sl', 'name': 'Sierra Leone'},
  <String, dynamic>{'id': 196, 'code': 'sg', 'name': 'Singapore'},
  <String, dynamic>{'id': 197, 'code': 'sk', 'name': 'Slovakia'},
  <String, dynamic>{'id': 198, 'code': 'si', 'name': 'Slovenia'},
  <String, dynamic>{'id': 199, 'code': 'sb', 'name': 'Solomon Islands'},
  <String, dynamic>{'id': 200, 'code': 'so', 'name': 'Somalia'},
  <String, dynamic>{'id': 201, 'code': 'za', 'name': 'South Africa'},
  <String, dynamic>{'id': 202, 'code': 'gs', 'name': 'South Georgia And Sandwich Isl.'},
  <String, dynamic>{'id': 203, 'code': 'ss', 'name': 'South Sudan'},
  <String, dynamic>{'id': 204, 'code': 'es', 'name': 'Spain'},
  <String, dynamic>{'id': 205, 'code': 'lk', 'name': 'Sri Lanka'},
  <String, dynamic>{'id': 206, 'code': 'sd', 'name': 'Sudan'},
  <String, dynamic>{'id': 207, 'code': 'sr', 'name': 'Suriname'},
  <String, dynamic>{'id': 208, 'code': 'sj', 'name': 'Svalbard And Jan Mayen'},
  <String, dynamic>{'id': 209, 'code': 'sz', 'name': 'Swaziland'},
  <String, dynamic>{'id': 210, 'code': 'se', 'name': 'Sweden'},
  <String, dynamic>{'id': 211, 'code': 'ch', 'name': 'Switzerland'},
  <String, dynamic>{'id': 212, 'code': 'sy', 'name': 'Syrian Arab Republic'},
  <String, dynamic>{'id': 213, 'code': 'tw', 'name': 'Taiwan'},
  <String, dynamic>{'id': 214, 'code': 'tj', 'name': 'Tajikistan'},
  <String, dynamic>{'id': 215, 'code': 'tz', 'name': 'Tanzania'},
  <String, dynamic>{'id': 216, 'code': 'th', 'name': 'Thailand'},
  <String, dynamic>{'id': 217, 'code': 'tl', 'name': 'TimorLeste'},
  <String, dynamic>{'id': 218, 'code': 'tg', 'name': 'Togo'},
  <String, dynamic>{'id': 219, 'code': 'tk', 'name': 'Tokelau'},
  <String, dynamic>{'id': 220, 'code': 'to', 'name': 'Tonga'},
  <String, dynamic>{'id': 221, 'code': 'tt', 'name': 'Trinidad And Tobago'},
  <String, dynamic>{'id': 222, 'code': 'tn', 'name': 'Tunisia'},
  <String, dynamic>{'id': 223, 'code': 'tr', 'name': 'Turkey'},
  <String, dynamic>{'id': 224, 'code': 'tm', 'name': 'Turkmenistan'},
  <String, dynamic>{'id': 225, 'code': 'tc', 'name': 'Turks And Caicos Islands'},
  <String, dynamic>{'id': 226, 'code': 'tv', 'name': 'Tuvalu'},
  <String, dynamic>{'id': 227, 'code': 'ug', 'name': 'Uganda'},
  <String, dynamic>{'id': 228, 'code': 'ua', 'name': 'Ukraine'},
  <String, dynamic>{'id': 229, 'code': 'ae', 'name': 'United Arab Emirates'},
  <String, dynamic>{'id': 230, 'code': 'gb', 'name': 'United Kingdom'},
  <String, dynamic>{'id': 231, 'code': 'us', 'name': 'United States'},
  <String, dynamic>{'id': 232, 'code': 'um', 'name': 'United States Outlying Islands'},
  <String, dynamic>{'id': 233, 'code': 'uy', 'name': 'Uruguay'},
  <String, dynamic>{'id': 234, 'code': 'uz', 'name': 'Uzbekistan'},
  <String, dynamic>{'id': 235, 'code': 'vu', 'name': 'Vanuatu'},
  <String, dynamic>{'id': 236, 'code': 've', 'name': 'Venezuela'},
  <String, dynamic>{'id': 237, 'code': 'vn', 'name': 'Vietnam'},
  <String, dynamic>{'id': 238, 'code': 'vg', 'name': 'Virgin Islands, British'},
  <String, dynamic>{'id': 239, 'code': 'vi', 'name': 'Virgin Islands, U.S.'},
  <String, dynamic>{'id': 240, 'code': 'wf', 'name': 'Wallis And Futuna'},
  <String, dynamic>{'id': 241, 'code': 'eh', 'name': 'Western Sahara'},
  <String, dynamic>{'id': 242, 'code': 'ye', 'name': 'Yemen'},
  <String, dynamic>{'id': 243, 'code': 'zm', 'name': 'Zambia'},
  <String, dynamic>{'id': 244, 'code': 'zw', 'name': 'Zimbabwe'},
];
