arb-dir: lib/resources/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: missing_translations.txt
preferred-supported-locales:
  - en
nullable-getter: false