/// Flutter icons EFotball
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EFotball
///      fonts:
///       - asset: fonts/EFotball.ttf
///
///
///
import 'package:flutter/widgets.dart';

class EFotball {
  EFotball._();

  static const _kFontFam = 'EFotball';

  static const IconData ball = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData check = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData clock = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData clubs = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData gamepad = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData logoWithName = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData logo = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData profile = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData streams = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData tournament = IconData(0xe809, fontFamily: _kFontFam);
}
