// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTy99RPZZGak6ckrH_2vUKHh5eaCbs55g',
    appId: '1:732744668889:web:a42fec17aeaae0026410c8',
    messagingSenderId: '732744668889',
    projectId: 'efotball-8e3d2',
    authDomain: 'efotball-8e3d2.firebaseapp.com',
    storageBucket: 'efotball-8e3d2.appspot.com',
    measurementId: 'G-005Z2LFBLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7EcvBLnPLGNkYyYqhkP-JM4yIWLeytQM',
    appId: '1:732744668889:android:9434b8d5833763016410c8',
    messagingSenderId: '732744668889',
    projectId: 'efotball-8e3d2',
    storageBucket: 'efotball-8e3d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_9Z6ovT9rPTPHZpMJDYDcktpWCu2L6Yk',
    appId: '1:732744668889:ios:cefc95da1894655a6410c8',
    messagingSenderId: '732744668889',
    projectId: 'efotball-8e3d2',
    storageBucket: 'efotball-8e3d2.appspot.com',
    iosClientId: '732744668889-h1aeekmu01bhqglok3ldn860k3ulrck6.apps.googleusercontent.com',
    iosBundleId: 'se.efotboll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_9Z6ovT9rPTPHZpMJDYDcktpWCu2L6Yk',
    appId: '1:732744668889:ios:cefc95da1894655a6410c8',
    messagingSenderId: '732744668889',
    projectId: 'efotball-8e3d2',
    storageBucket: 'efotball-8e3d2.appspot.com',
    iosClientId: '732744668889-h1aeekmu01bhqglok3ldn860k3ulrck6.apps.googleusercontent.com',
    iosBundleId: 'se.efotboll',
  );
}
